apiVersion: apps/v1
kind: Deployment

metadata:
  name: dotnet-currency-conversion

spec:
  replicas: 2

  selector:
    matchLabels:
      app: dotnet-currency-conversion

  template:
    metadata:
      labels:
        app: dotnet-currency-conversion

    spec:
      containers:
      - name: dotnet-currency-conversion

        image: goyalrohitcece/currency-conversion:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080