apiVersion: v1
kind: Service

metadata:
  name: dotnet-service-currency-conversion

spec:

  selector:
    app: dotnet-currency-conversion

  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31635
    
  type: LoadBalancer
  # type: NodePort